In [45]:
import pandas as pd

df = pd.read_csv(r'C:\Users\eajaj\Downloads\-Human-AI-Technical-Test-\outputs\features_dataset.csv')

print(df.shape)
df.head()

(200, 70)

,filepath,filename,modality,vocal_channel,emotion_code,emotion_label,intensity,statement,repetition,actor,...,zcr_std,rms_energy_mean,rms_energy_std,rms_energy_max,chroma_mean,chroma_std,tempo_bpm,speech_ratio,silence_ratio,num_segments
0,data\ravdess\Audio_Speech_Actors_01-24\Actor_0...,03-01-01-01-01-01-01.wav,3,1,1,neutral,normal,kids,1,1,...,0.267766,0.002256,0.003289,0.012585,0.598354,0.295375,80.7495,0.3936,0.6064,1
1,data\ravdess\Audio_Speech_Actors_01-24\Actor_0...,03-01-01-01-01-02-01.wav,3,1,1,neutral,normal,kids,2,1,...,0.271137,0.002419,0.003526,0.013047,0.578001,0.298424,161.4990,0.3897,0.6103,1
2,data\ravdess\Audio_Speech_Actors_01-24\Actor_0...,03-01-01-01-02-01-01.wav,3,1,1,neutral,normal,dogs,1,1,...,0.287049,0.002809,0.004224,0.017971,0.590222,0.298249,80.7495,0.3906,0.6094,1
3,data\ravdess\Audio_Speech_Actors_01-24\Actor_0...,03-01-01-01-02-02-01.wav,3,1,1,neutral,normal,dogs,2,1,...,0.277524,0.002617,0.004103,0.018385,0.572797,0.281639,64.5996,0.3882,0.6118,1
4,data\ravdess\Audio_Speech_Actors_01-24\Actor_0...,03-01-02-01-01-01-01.wav,3,1,2,calm,normal,kids,1,1,...,0.276072,0.001653,0.002440,0.010988,0.561585,0.303143,117.4538,0.4399,0.5601,1

In [46]:
df[["duration_sec", "pitch_mean_hz", "rms_energy_mean"]].describe()

       duration_sec  pitch_mean_hz  rms_energy_mean
count    200.000000     200.000000       200.000000
mean       3.750100     523.557611         0.010436
std        0.290573     146.753851         0.012641
min        3.169800     183.450100         0.001501
25%        3.536900     416.103000         0.003269
50%        3.737100     512.772650         0.006497
75%        3.937300     630.849375         0.011202
max        5.005000     883.859500         0.092270

In [47]:
print(df.columns)

Index(['filepath', 'filename', 'modality', 'vocal_channel', 'emotion_code',
       'emotion_label', 'intensity', 'statement', 'repetition', 'actor',
       'duration_sec', 'mfcc_1_mean', 'mfcc_1_std', 'mfcc_2_mean',
       'mfcc_2_std', 'mfcc_3_mean', 'mfcc_3_std', 'mfcc_4_mean', 'mfcc_4_std',
       'mfcc_5_mean', 'mfcc_5_std', 'mfcc_6_mean', 'mfcc_6_std', 'mfcc_7_mean',
       'mfcc_7_std', 'mfcc_8_mean', 'mfcc_8_std', 'mfcc_9_mean', 'mfcc_9_std',
       'mfcc_10_mean', 'mfcc_10_std', 'mfcc_11_mean', 'mfcc_11_std',
       'mfcc_12_mean', 'mfcc_12_std', 'mfcc_13_mean', 'mfcc_13_std',
       'delta_mfcc_1_mean', 'delta_mfcc_2_mean', 'delta_mfcc_3_mean',
       'delta_mfcc_4_mean', 'delta_mfcc_5_mean', 'delta_mfcc_6_mean',
       'delta_mfcc_7_mean', 'delta_mfcc_8_mean', 'delta_mfcc_9_mean',
       'delta_mfcc_10_mean', 'delta_mfcc_11_mean', 'delta_mfcc_12_mean',
       'delta_mfcc_13_mean', 'pitch_mean_hz', 'pitch_std_hz', 'pitch_range_hz',
       'voiced_fraction', 'spectral_centroid_mean', 'spectral_centroid_std',
       'spectral_bandwidth_mean', 'spectral_rolloff_mean',
       'spectral_contrast_mean', 'zcr_mean', 'zcr_std', 'rms_energy_mean',
       'rms_energy_std', 'rms_energy_max', 'chroma_mean', 'chroma_std',
       'tempo_bpm', 'speech_ratio', 'silence_ratio', 'num_segments'],
      dtype='str')

In [55]:
import seaborn as sns
import matplotlib.pyplot as plt

plt.figure()
sns.boxplot(x="emotion_label", y="rms_energy_mean", data=df)
plt.xticks(rotation=45)
plt.show()

In [56]:
sns.boxplot(x="emotion_label", y="rms_energy_mean", data=df)

In [50]:
plt.figure()
sns.boxplot(x="emotion_label", y="pitch_mean_hz", data=df)
plt.xticks(rotation=45)
plt.title("Pitch vs Emotion")
plt.show()

Observation:
 Angry and happy speech show higher energy
 Calm/neutral have lower variation

In [51]:
df.describe()

,modality,vocal_channel,emotion_code,repetition,actor,duration_sec,mfcc_1_mean,mfcc_1_std,mfcc_2_mean,mfcc_2_std,...,zcr_std,rms_energy_mean,rms_energy_std,rms_energy_max,chroma_mean,chroma_std,tempo_bpm,speech_ratio,silence_ratio,num_segments
count,200.0,200.0,200.000000,200.000000,200.000000,200.000000,200.000000,200.000000,200.000000,200.000000,...,200.000000,200.000000,200.000000,200.000000,200.000000,200.000000,200.000000,200.000000,200.000000,200.000000
mean,3.0,1.0,4.480000,1.500000,2.200000,3.750100,-570.512431,178.462384,49.728882,56.181570,...,0.225032,0.010436,0.013917,0.056181,0.465594,0.324609,130.152557,0.469181,0.530820,1.530000
std,0.0,0.0,2.216793,0.501255,0.982255,0.290573,97.691503,15.827897,12.166931,9.855395,...,0.055431,0.012641,0.016415,0.064585,0.067772,0.020310,38.018021,0.047190,0.047190,0.850126
min,3.0,1.0,1.000000,1.000000,1.000000,3.169800,-735.523987,133.992584,15.558997,28.126154,...,0.069374,0.001501,0.001883,0.006752,0.329289,0.280034,52.734400,0.357200,0.349000,1.000000
25%,3.0,1.0,3.000000,1.000000,1.000000,3.536900,-650.913742,169.487557,43.176713,49.655813,...,0.195924,0.003269,0.004569,0.018416,0.413982,0.308810,103.359400,0.439900,0.509675,1.000000
50%,3.0,1.0,4.000000,1.500000,2.000000,3.737100,-581.676972,180.339638,49.892568,56.877134,...,0.239472,0.006497,0.008870,0.033663,0.469514,0.322902,129.199200,0.461900,0.538100,1.000000
75%,3.0,1.0,6.000000,2.000000,3.000000,3.937300,-517.693786,190.346287,58.166782,61.977743,...,0.269015,0.011202,0.014733,0.057373,0.511824,0.341921,161.499000,0.490325,0.560100,2.000000
max,3.0,1.0,8.000000,2.000000,4.000000,5.005000,-303.908295,211.130219,80.508270,77.897346,...,0.310055,0.092270,0.116866,0.415087,0.608816,0.367979,234.907700,0.651000,0.642800,6.000000

Insight:
 Average duration 4–5 seconds
 Energy varies significantly across samples

In [52]:
df["emotion_label"].value_counts().plot(kind="bar")
plt.title("Emotion Distribution")
plt.show()

Observation:
Dataset is relatively balanced , good for classification

In [53]:
results = pd.read_csv(r'C:\Users\eajaj\Downloads\-Human-AI-Technical-Test-\outputs\model_comparison.csv')
results

                 Model  CV_F1_mean  CV_F1_std  Test_Acc  Test_F1
0  Logistic Regression      0.7120     0.0849     0.800   0.7874
1        Random Forest      0.6714     0.0601     0.875   0.8838
2    Gradient Boosting      0.6409     0.0156     0.850   0.8494
3            SVM (RBF)      0.6723     0.0711     0.850   0.8371

In [54]:
from PIL import Image
import matplotlib.pyplot as plt

img = Image.open("../outputs/confusion_matrix.png")
plt.imshow(img)
plt.axis("off")
plt.title("Confusion Matrix")

Text(0.5, 1.0, 'Confusion Matrix')

Model Insight:
 SVM achieved best performance (F1 ≈ 0.83)
 Calm speech is easiest to classify
 Urgency and suspense show confusion due to similar energy patterns